config/routes.rb
Rails.application.routes.draw do

  resources :room_messages
  devise_for :users , :controllers => { registrations: 'edit_customs' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'edit_customs#edit'
  end

  # Devise (login/logout) for HTML requests
  # devise_for :users, defaults: { format: :html },
  #                        path: '',
  #                  path_names: { sign_up: 'register' },
  #                 controllers: {
  #                   sessions: 'sessions',
  #                   registrations: 'edit_customs',
  #                   confirmations: 'confirmations'
  #                 }
  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'register', to: 'devise/registrations#new'
  #   post 'register', to: 'devise/registrations#create'
  #   delete 'sign_out', to: 'devise/sessions#destroy'
  #   get 'confirmation/sent', to: 'confirmations#sent'
  #   get 'confirmation/:confirmation_token', to: 'confirmations#show'
  #   patch 'confirmation', to: 'confirmations#create'
  # end

  # API namespace, for JSON requests at /api/sign_[in|out]
  namespace :api do
    devise_for :users, defaults: { format: :json },
                     class_name: 'ApiUser',
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: '',
                     path_names: { sign_in: 'login',
                                  sign_out: 'logout' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      delete 'logout', to: 'devise/sessions#destroy'
    end
  end

  root 'pages#home'

  resources :cars
  resources :rentals
  get '/search' => 'pages#search', :as => 'search_page'
  get :search_json, controller: :main

  get '/myrentals/:id', to: 'rentals#show_as_renter', as: "show_as_renter"

  resources :cars_app
  resources :rentals_app

  get '/myrentals_app/:id', to: 'rentals_app#show_as_renter', as: "show_as_renter_from_app"

  resources :charges
  #post '/authentication_tokens', to: "authentication_tokens#create"

  resources :room_messages


  resources :rentals_step
  
  get '/stepA/:id' => 'rentals_step#stepA', as: "stepA"
  get '/stepB/:id' => 'rentals_step#stepB', as: "stepB"
  get '/stepC/:id' => 'rentals_step#stepC', as: "stepC"
  get '/stepD/:id' => 'rentals_step#stepD', as: "stepD"
  get '/stepE/:id' => 'rentals_step#stepE', as: "stepE"
  post '/create_open_traccar' => 'rentals_step#create_open_traccar'


  resources :dashboard
  get '/gettoken' => 'dashboard#create_auth_code', :as => 'gettoken' #A transformer en post pour stocker token n°2 dans database
  get '/login_token' => 'dashboard#create_token', :as => 'login_token' #A transformer en post pour stocker token n°2 dans database
  get '/mifleetcars' => 'dashboard#mifleetcars', :as => 'mifleetcars'
  put '/update_car_device' => 'dashboard#update_car_device'

  get :customer, controller: :dashboard
  get '/customer/:id' => 'dashboard#show_customer', :as => 'getcustomer'
  get :vehicle, controller: :dashboard
  get :orders, controller: :dashboard
  get '/statistics'  => 'dashboard#statistics'

  get 'search_customer', to: 'dashboard#search_customer', defaults: { format: 'js' }
  get 'search_vehicle', to: 'dashboard#search_vehicle', defaults: { format: 'js' }
  get 'search_orders', to: 'dashboard#search_orders', defaults: { format: 'js' }
  get 'search_traccar', to: 'traccar#search_traccar', defaults: { format: 'js' }
  get 'search_traccar_connected', to: 'traccar#search_traccar_connected', defaults: { format: 'js' }


  resources :license
  resources :traccar
  get '/traccar_edit/:id' => 'traccar#traccar_edit', as: "traccar_edit"
  post '/traccar_command' => 'traccar#traccar_command'
  post '/add_traccar_device' => 'traccar#add_traccar_device'
  put '/add_device_id' => 'traccar#add_device_id'
  get '/traccar_api' => 'traccar#traccar_api'

  resources :verification
  #get :submit_verification, controller: :verification


end

app/controllers/dashboard_controller.rb
require 'oauth2'
require 'base64'
require 'uri'
require 'net/http'
require 'openssl'


class DashboardController < ApplicationController
    before_action :authenticate_user!
    before_action :set_xee_data, only: [:create_auth_code, :create_token, :create_token_curl]



    def index
        authorize User
    end

    def mifleetcars
        authorize User
        @cars = Car.all
    end

    def update_car_device
        authorize User
        if params[:device_id] == ""
            flash[:alert] = "Le device id est vide"
            redirect_to request.referrer
        else
            @car = Car.find(params[:car])
            if @car.update_attribute(:device_id,params[:device_id]) && @car.update_attribute(:society,"MiFleetXee")
                flash[:notice] = "Le device id du vehicule #{@car.name} a été modifié avec succès!"

                redirect_to mifleetcars_path
            else
                flash[:alert] = "Le device id du vehicule #{@car.name} n'a pas été modifé avec succès!"
                redirect_to request.referrer
            end
        end


    end


    def create_auth_code
        authorize User
        puts "I'm starting the GetXeeTokkenAccessJob job"


        session[:carA]= params[:carA]
        session[:carB]= params[:carB]
        session[:carC]= params[:carC]
        session[:account] = params[:account]
        puts "J'ai peter"
        if session[:account] == "compte1"
            puts ("compte1 aouth")
            @client = OAuth2::Client.new('82691cc6ca56aef8108137b13c6ce19d', 'a625efd93280973580ccf96acfc81b4d0cfc19a3379cde9e425f3ae5d113b2a9', site: 'https://api.xee.com', token_url: '/v4/oauth/token', authorize_url: '/v4/oauth/authorize')
            u = @client.auth_code.authorize_url(scope: 'vehicles.read vehicles.management vehicles.signals.read vehicles.locations.read vehicles.accelerometers.read vehicles.privacies.read vehicles.privacies.management vehicles.trips.read vehicles.loans.read vehicles.loans.management account.read vehicles.signals.summaries.read', redirect_uri: 'http://127.0.0.1:3005/login_token')
        elsif session[:account] == "compte2"
            puts ("compte2 aouth")
            @client = OAuth2::Client.new('aa06c7da19524436b5d40859b9e4f701', '0e4dc2f93910fd82270c9034207cabc1e1aea8c892adf1b4ccb7094173d7eeb3', site: 'https://api.xee.com', token_url: '/v4/oauth/token', authorize_url: '/v4/oauth/authorize')
            u = @client.auth_code.authorize_url(scope: 'vehicles.read vehicles.management vehicles.signals.read vehicles.locations.read vehicles.accelerometers.read vehicles.privacies.read vehicles.privacies.management vehicles.trips.read vehicles.loans.read vehicles.loans.management account.read vehicles.signals.summaries.read', redirect_uri: 'http://127.0.0.1:3005/login_token')
        end
        puts u

        redirect_to u

    end

    def create_token_curl
        code = params[:code]
        url = URI("https://api.xee.com/v4/oauth/token")

        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE

        request = Net::HTTP::Post.new(url)
        request.add_field("Authorization", "Basic ODI2OTFjYzZjYTU2YWVmODEwODEzN2IxM2M2Y2UxOWQ6YTYyNWVmZDkzMjgwOTczNTgwY2NmOTZhY2ZjODFiNGQwY2ZjMTlhMzM3OWNkZTllNDI1ZjNhZTVkMTEzYjJhOQ==")
        request["content-type"] = 'application/x-www-form-urlencoded'   
        puts ("hello 1")
        request.body = "grant_type=authorization_code&code=#{code}"
        puts ("hello 2")
        response = http.request(request)
        puts ("hello 3")
        puts response.read_body
        puts ("hello 4")

        redirect_to dashboard_index_path

    end
    def create_token

        authorize User

        code = params[:code]

        #puts "J'ai peter 2"
        # # => "https://example.org/oauth/authorization?response_type=code&client_id=client_id&redirect_uri=http://localhost:8080/oauth2/callback"

        if session[:account] == "compte1"
            puts ("compte1 entrer")
            @client = OAuth2::Client.new('82691cc6ca56aef8108137b13c6ce19d', 'a625efd93280973580ccf96acfc81b4d0cfc19a3379cde9e425f3ae5d113b2a9', site: 'https://api.xee.com', token_url: '/v4/oauth/token', authorize_url: '/v4/oauth/authorize')
            response = @client.auth_code.get_token( code , grant_type: "authorization_code",  headers: {'Authorization' => "Basic ODI2OTFjYzZjYTU2YWVmODEwODEzN2IxM2M2Y2UxOWQ6YTYyNWVmZDkzMjgwOTczNTgwY2NmOTZhY2ZjODFiNGQwY2ZjMTlhMzM3OWNkZTllNDI1ZjNhZTVkMTEzYjJhOQ==" })
        elsif  session[:account] == "compte2"
            puts ("compte2 entrer")
            @client = OAuth2::Client.new('aa06c7da19524436b5d40859b9e4f701', '0e4dc2f93910fd82270c9034207cabc1e1aea8c892adf1b4ccb7094173d7eeb3', site: 'https://api.xee.com', token_url: '/v4/oauth/token', authorize_url: '/v4/oauth/authorize')
            response = @client.auth_code.get_token( code , grant_type: "authorization_code",  headers: {'Authorization' => "Basic YWEwNmM3ZGExOTUyNDQzNmI1ZDQwODU5YjllNGY3MDE6MGU0ZGMyZjkzOTEwZmQ4MjI3MGM5MDM0MjA3Y2FiYzFlMWFlYThjODkyYWRmMWI0Y2NiNzA5NDE3M2Q3ZWViMw==" })
        else 
            flash[:alert] = "Token fail"
            redirect_to request.referrer
        end
        
            #puts "g p t 3"
        # response = token.get('/api/resource', params: {'query_foo' => 'bar'})
        # puts response
        # # => OAuth2::Response
        token = response.to_hash[:access_token]

        puts ("token")
        puts token

        if Car.find(session[:carA]).update_attribute(:XeeAccessTokken,token) && Car.find(session[:carB]).update_attribute(:XeeAccessTokken,token) && Car.find(session[:carC]).update_attribute(:XeeAccessTokken,token)
            flash[:notice] = "Token success"

            redirect_to mifleetcars_path
        else
            flash[:alert] = "Token fail"
            redirect_to request.referrer
        end


        # puts "OK I'm done now"
        # puts ("params code")
        # puts params["code"]
        # creer token
        # enregister token dans db
    end

    
    def customer
        @users = User.order(created_at: :asc).page(params[:page])
    end

    def getcustomer
        @user = User.find(params[:id])
    end

    def show_customer
        @user = User.find(params[:id])
        @verifications = Verification.where(:user_id => @user.id)
        @cars = Car.where(:user_id => @user.id)
        @rentals = Rental.where(:user_id => @user.id)
    end

    def vehicle
        @cars = Car.order(created_at: :asc).page(params[:page])
    end

    def orders
        @rentals = Rental.order(created_at: :asc).page(params[:page])
    end

    def search_customer
        query = params[:search_customer]
        @users = User.where('email LIKE ?', "%#{query}%")
  
    end

    def search_vehicle
        query = params[:search_vehicle]
        @cars = Car.where('name LIKE ?', "%#{query}%")

    end

    def search_orders
        query = params[:search_orders]
        @rentals = Rental.where('id LIKE ?', "%#{query}%")
        #render layout: false
    end

    def statistics
        @rentals = Rental.all
        @cars = Car.all
        @data = User.group_by_week(:created_at).count
        accumulator = 0
        @data.transform_values! do |val|
            val += accumulator
            accumulator = val
        end

    end

    def traccar_lock 
        @open_door_traccars = OpenDoorTraccar.all
    end
    

    private

    def set_xee_data
        puts ("data xee before action")
        @client_id     = '82691cc6ca56aef8108137b13c6ce19d' # your client’s id generated with rake db:setup
        @client_secret = 'a625efd93280973580ccf96acfc81b4d0cfc19a3379cde9e425f3ae5d113b2a9'
        @auth = 'Basic ' + Base64.encode64("#{@client_id}:#{@client_secret}") #issue with line jump instead same line
        
    end


end

app/views/dashboard/_customer.html.erb
 <div class="list-items item-card-pc hidden-xs">
    <table>
        <caption>Liste des clients</caption>

        <tr>
            <th scope="col">Photo</th>
            <th scope="col">Email</th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Mobile</th>
            <th scope="col">Role</th>
            <th scope="col">Créé le</th>
            <th scope="col"></th>
        <tr>
        <% @users.each do |user| %>
            <tr>
                <td class="item-image"><%= image_tag user.avatar_thumbnail, class: "image-pp" %></td>
                <th scope="row" class="item-name">
                    <%= link_to getcustomer_path(user) , class:"" do %>
                        <%= user.email %>
                    <% end %>
                </th>
                <td class="item-info"><%= user.name %></td>
                <td class="item-info"><%= user.firstname %></td>
                <td class="item-info"><%= user.phone %></td>
                <td class="item-info"><%= user.role %></td>
                <td class="item-info"><%= user.created_at %></td>
                <td>
                    <%= link_to ('<i class="fas fa-edit fa-2x"></i>').html_safe, '#' %>
                    <%= link_to ('<i class="fas fa-trash-alt fa-2x"></i>').html_safe, '#',class:"", method: :delete, :onclick => "return confirm('Etes vous sur?')", :remote => true %>
                </td>
            </tr>

            
        <% end %>
    </table>
</div>

 <div class="list-items item-card-pc hidden-md hidden-lg hidden-sm">
    <table>
        <caption>Liste des clients</caption>

        <tr>
            <th scope="col">Photo</th>
            <th scope="col">Email</th>
            <th scope="col">Mobile</th>
            <th scope="col">Role</th>
            <th scope="col"></th>
        <tr>
        <% @users.each do |user| %>
            <tr>
                <td class="item-image"><%= image_tag user.avatar_thumbnail, class: "image-pp" %></td>
                <th scope="row" class="item-name">
                    <%= link_to getcustomer_path(user) , class:"" do %>
                        <%= user.email %>
                    <% end %>
                </th>
                <td class="item-info"><%= user.phone %></td>
                <td class="item-info"><%= user.role %></td>
                <td>
                    <%= link_to ('<i class="fas fa-edit fa-2x"></i>').html_safe, '#' %>
                    <%= link_to ('<i class="fas fa-trash-alt fa-2x"></i>').html_safe, '#',class:"", method: :delete, :onclick => "return confirm('Etes vous sur?')", :remote => true %>
                </td>
            </tr>

            
        <% end %>
    </table>
</div>

app/views/dashboard/_orders.html.erb
<div class="list-items item-card-pc">
    <table>
        <caption>Liste des commandes</caption>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Client</th>
            <th scope="col">Voiture</th>
            <th scope="col">Date de départ</th>
            <th scope="col">Date de fin</th>
            <th scope="col">Prix de la location</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
        <tr>
        <% @rentals.each do |rental| %>
            <tr>
                <th scope="row" class="item-name"><%= rental.id %></th>
                <td class="item-info"><%= rental.user.email %></td>
                <td class="item-image"><%= image_tag rental.car.cars_thumbnail.first , class: "image-pp" %></td>
                <td class="item-info"><%= rental.starts_on %></td>
                <td class="item-info"><%= rental.ends_on %></td>
                <td class="item-info"><%= rental.total_price_cents %></td>
                <td class="item-info"><%= rental.status %></td>
                <td>
                    <%= link_to ('<i class="fas fa-edit fa-2x"></i>').html_safe, '#' %>
                    <%= link_to ('<i class="fas fa-trash-alt fa-2x"></i>').html_safe, '#',class:"", method: :delete, :onclick => "return confirm('Etes vous sur?')", :remote => true %>
                </td>
            </tr>

            
        <% end %>
    </table>
</div>

app/views/dashboard/_vehicle.html.erb
<div class="list-items item-card-pc">
    <table>
        <caption>Liste des véhicules</caption>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col">Nom</th>
            <th scope="col">Plaque</th>
            <th scope="col">Adresse</th>
            <th scope="col">Année</th>
            <th scope="col">Type</th>
            <th scope="col">Prix</th>
            <th scope="col">Prix par km</th>
            <th scope="col">Propriétaire</th>
            <th scope="col">Société</th>
            <th scope="col"></th>
        <tr>
        <% @cars.each do |car| %>
            <tr>
                <td class="item-image"><%= image_tag car.cars_thumbnail.first, class: "image-pp" %></td>
                <th scope="row" class="item-name"><%= car.name %></th>
                <td class="item-info"><%= car.plaque %></td>
                <td class="item-info"><%= car.address %></td>
                <td class="item-info"><%= car.year %></td>
                <td class="item-info"><%= car.type_car %></td>
                <td class="item-info"><%= car.price_cents %></td>
                <td class="item-info"><%= car.price_by_km %></td>
                <td class="item-info"><%= car.user.email %></td>
                <td class="item-info"><%= car.society %></td>
                <td>
                    <%= link_to ('<i class="fas fa-edit fa-2x"></i>').html_safe, '#' %>
                    <%= link_to ('<i class="fas fa-trash-alt fa-2x"></i>').html_safe, '#',class:"", method: :delete, :onclick => "return confirm('Etes vous sur?')", :remote => true %>
                </td>
            </tr>

            
        <% end %>
    </table>
</div>

app/views/dashboard/customer.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Clients</h2>
       
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
        <%= form_tag(search_customer_path, method: "get", remote: true) do %>
            <div class="input-group mb-5">
                <div class="col-8" style="padding:0">
                    <%= text_field_tag :search_customer, '', class:'form-control', placeholder: 'Recherche de client ...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4" style="padding:0">
                    <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit', style:'display:none'%>
                </div>
            </div>
        <% end %>
        
        <div id="menu-customer-container">
            <%= render 'customer'%>
        </div>


    </div>


</div>

<script>
    function clickSubmit() {
        $("#search_submit").trigger("click");
    }
</script>

app/views/dashboard/mifleetcars.html.erb
<%= form_with url: "/update_car_device", method: :put do |form| %>
    <%= form.label :device_id, "device id" %>
    <%= form.text_field :device_id %>
    <%= form.label :car, "Choisis un véhicule MiFleet" %>
    <%= form.collection_select :car, @cars , :id, :name %>
    <%= form.submit "Ajouter" %>
<% end %>



<%= form_with url: "/gettoken", method: :get do |f| %>
    <label>Renseigner les véhicules MiFleet</label>
    <%= f.collection_select  :carA, @cars , :id, :name %>
    <%= f.collection_select  :carB, @cars , :id, :name %>
    <%= f.collection_select  :carC, @cars , :id, :name %>
    <label>Renseigner le compte Xee</label>
    <%= f.select(:account, options_for_select([ "compte1", "compte2", "compte3" ])) %>
    <%= f.submit "get token" %>
<% end %>

app/views/dashboard/orders.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Commandes</h2>
        <%= paginate @rentals, theme: 'twitter-bootstrap-4' %>
        <%= form_tag(search_orders_path, method: "get", remote: true, style:'display:none') do %>
            <div class="input-group mb-5">
                <div class="col-8" style="padding:0">
                    <%= text_field_tag :search_orders, '', class:'form-control', placeholder: 'Recherche de commandes ...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4" style="padding:0">
                    <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit', style:'display:none'%>
                </div>
            </div>
        <% end %>
 

                
        <div id="menu-orders-container">
            <%= render 'orders'%>
        </div>

    </div>


</div>

app/views/dashboard/search_customer.js.erb
$("#menu-customer-container").html("<%= j render 'customer' %>");

app/views/dashboard/search_orders.js.erb
$("#menu-orders-container").html("<%= j render 'orders' %>");

app/views/dashboard/search_vehicle.js.erb
$("#menu-vehicle-container").html("<%= j render 'vehicle' %>");

app/views/dashboard/show_customer.html.erb
<div class="dashboard">   
    <div class="page-customer">
        <div class="title-customer">
            <h2>Informations personnelles</h2>
        </div>

        <div class="bloc-customer">
            <h4 class="text-customer">Informations générales</h4>
            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Photo</h3>
                
            </div>
            <div class="line-customer"></div>

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Nom</h3>
                <h3 class=text-response-info-customer><%= @user.firstname %></h3>
            </div>
            <div class="line-customer"></div>

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Prénom</h3>
                <h3 class=text-response-info-customer><%= @user.name %></h3>
            </div>
            <div class="line-customer"></div>

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Créé le</h3>
                <h3 class=text-response-info-customer><%= @user.created_at %></h3>
            </div>


        </div>



        <div class="bloc-customer">
            <h4 class="text-customer">Coordonnées</h4>
            
            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Téléphone</h3>
                <h3 class=text-response-info-customer><%= @user.phone %></h3>
            </div>
            <div class="line-customer"></div>

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Email</h3>
                <h3 class=text-response-info-customer><%= @user.email %></h3>
            </div>


        </div>

        

        <div class="bloc-customer">
            <h4 class="text-customer">Voitures</h4>
            <div class="customer-all-cars-bloc">
                <% @cars.each do |car| %>
                    <div class="customer-car-bloc">
                        <%= image_tag car.cars_thumbnail.first, class: "car-customer-image" %>
                        <h3 class="plaque-car-customer"><%= car.plaque %></h3>
                    </div>
                <% end %>

            </div>
        </div>


        <div class="bloc-customer">
            <h4 class="text-customer">Vérifications</h4>
      

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>CNI</h3>
                <% if @user.cni == "not_verified" %>
                    <h3 class="text-response-info-customer notverified-color">En attente de vérification</h3>
                <% elsif @user.cni == "manual" %>
                    <h3 class="text-response-info-customer manual-color">En attente de validation</h3>
                <% elsif @user.cni == "verified" %>
                    <h3 class="text-response-info-customer validated-color">CNI validée</h3>
                <% else %>
                    <h3 class="text-response-info-customer">Pas de données</h3>
                <% end %>
            </div>
            <div class="line-customer"></div>

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>License</h3>
                <% if @user.license == "not_verified" %>
                    <h3 class="text-response-info-customer notverified-color">En attente de vérification</h3>
                <% elsif @user.license == "manual" %>
                    <h3 class="text-response-info-customer manual-color">En attente de validation</h3>
                <% elsif @user.license == "verified" %>
                    <h3 class="text-response-info-customer validated-color">Permis de conduire validé</h3>
                <% else %>
                    <h3 class="text-response-info-customer">Pas de données</h3>
                <% end %>
            </div>
            <div class="line-customer"></div>

            <div class="bloc-info-customer">
                <h3 class=text-info-customer>Reconnaissance faciale</h3>
  
            </div>

        </div>

       


    </div>


</div>

app/views/dashboard/statistics.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Statistiques</h2>
       
        <div class="stats-card">
            <caption>Locations par mois</caption>
            <%= column_chart @rentals.group_by_month(:created_at, format: "%b %Y").count %>
        </div>

        <div class="stats-card">
            <caption>Bénéfices par mois</caption>
            <%= column_chart @rentals.group_by_month(:created_at, format: "%b %Y").sum(:total_price_cents) %>
        </div>

        <div class="stats-card">
            <caption>Nombre d'utilisateurs</caption>
            <%= line_chart @data %>
        </div>



    </div>


</div>

app/views/dashboard/traccar_lock.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Traccar lock</h2>
       
 
        <div class="list-items item-card-pc">
            <table>
                <caption>Traccar lock</caption>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Id location</th>
                    <th scope="col">Plaque voiture</th>
                    <th scope="col">Utilisateur</th>
                    <th scope="col">Door open</th>
                    <th scope="col">Anti-démarrage</th>
                    <th scope="col">Créé à</th>
                    <th scope="col">Modifié à</th>
                <tr>
                <% @rentals.each do |rental| %>
                    <tr>
                        <th scope="row" class="item-name"><%= rental.id %></th>
                        <td class="item-info"><%= rental.user.email %></td>
                        <td class="item-info"><%= rental.user.email %></td>
                        <td class="item-info"><%= rental.starts_on %></td>
                        <td class="item-info"><%= rental.ends_on %></td>
                        <td class="item-info"><%= rental.total_price_cents %></td>
                        <td class="item-info"><%= rental.status %></td>
                        <td class="item-info"><%= rental.status %></td>
                    </tr>

                    
                <% end %>
            </table>
        </div>

    </div>


</div>

app/views/dashboard/vehicle.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Voitures</h2>
        <%= paginate @cars, theme: 'twitter-bootstrap-4' %>
        <%= form_tag(search_vehicle_path, method: "get", remote: true) do %>
            <div class="input-group mb-5">
                <div class="col-8" style="padding:0">
                    <%= text_field_tag :search_vehicle, '', class:'form-control', placeholder: 'Recherche de voitures ...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4" style="padding:0">
                    <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit', style:'display:none'%>
                </div>
            </div>
        <% end %>
        
        <div id="menu-vehicle-container">
            <%= render 'vehicle'%>
        </div>


    </div>


</div>

<script>
    function clickSubmit() {
        $("#search_submit").trigger("click");
    }
</script>