config/routes.rb
Rails.application.routes.draw do

  resources :room_messages
  devise_for :users , :controllers => { registrations: 'edit_customs' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'edit_customs#edit'
  end

  # Devise (login/logout) for HTML requests
  # devise_for :users, defaults: { format: :html },
  #                        path: '',
  #                  path_names: { sign_up: 'register' },
  #                 controllers: {
  #                   sessions: 'sessions',
  #                   registrations: 'edit_customs',
  #                   confirmations: 'confirmations'
  #                 }
  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'register', to: 'devise/registrations#new'
  #   post 'register', to: 'devise/registrations#create'
  #   delete 'sign_out', to: 'devise/sessions#destroy'
  #   get 'confirmation/sent', to: 'confirmations#sent'
  #   get 'confirmation/:confirmation_token', to: 'confirmations#show'
  #   patch 'confirmation', to: 'confirmations#create'
  # end

  # API namespace, for JSON requests at /api/sign_[in|out]
  namespace :api do
    devise_for :users, defaults: { format: :json },
                     class_name: 'ApiUser',
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: '',
                     path_names: { sign_in: 'login',
                                  sign_out: 'logout' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      delete 'logout', to: 'devise/sessions#destroy'
    end
  end

  root 'pages#home'

  resources :cars
  resources :rentals
  get '/search' => 'pages#search', :as => 'search_page'
  get :search_json, controller: :main

  get '/myrentals/:id', to: 'rentals#show_as_renter', as: "show_as_renter"

  resources :cars_app
  resources :rentals_app

  get '/myrentals_app/:id', to: 'rentals_app#show_as_renter', as: "show_as_renter_from_app"

  resources :charges
  #post '/authentication_tokens', to: "authentication_tokens#create"

  resources :room_messages


  resources :rentals_step
  
  get '/stepA/:id' => 'rentals_step#stepA', as: "stepA"
  get '/stepB/:id' => 'rentals_step#stepB', as: "stepB"
  get '/stepC/:id' => 'rentals_step#stepC', as: "stepC"
  get '/stepD/:id' => 'rentals_step#stepD', as: "stepD"
  get '/stepE/:id' => 'rentals_step#stepE', as: "stepE"
  post '/create_open_traccar' => 'rentals_step#create_open_traccar'


  resources :dashboard
  get '/gettoken' => 'dashboard#create_auth_code', :as => 'gettoken' #A transformer en post pour stocker token n°2 dans database
  get '/login_token' => 'dashboard#create_token', :as => 'login_token' #A transformer en post pour stocker token n°2 dans database
  get '/mifleetcars' => 'dashboard#mifleetcars', :as => 'mifleetcars'
  put '/update_car_device' => 'dashboard#update_car_device'

  get :customer, controller: :dashboard
  get '/customer/:id' => 'dashboard#show_customer', :as => 'getcustomer'
  get :vehicle, controller: :dashboard
  get :orders, controller: :dashboard
  get '/statistics'  => 'dashboard#statistics'

  get 'search_customer', to: 'dashboard#search_customer', defaults: { format: 'js' }
  get 'search_vehicle', to: 'dashboard#search_vehicle', defaults: { format: 'js' }
  get 'search_orders', to: 'dashboard#search_orders', defaults: { format: 'js' }
  get 'search_traccar', to: 'traccar#search_traccar', defaults: { format: 'js' }
  get 'search_traccar_connected', to: 'traccar#search_traccar_connected', defaults: { format: 'js' }


  resources :license
  resources :traccar
  get '/traccar_edit/:id' => 'traccar#traccar_edit', as: "traccar_edit"
  post '/traccar_command' => 'traccar#traccar_command'
  post '/add_traccar_device' => 'traccar#add_traccar_device'
  put '/add_device_id' => 'traccar#add_device_id'
  get '/traccar_api' => 'traccar#traccar_api'

  resources :verification
  #get :submit_verification, controller: :verification


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    MiFleet Copyright 2021. Made with <i class="fas fa-heart"></i> in France
  </div>
</div>
 -->

 <div class="footer-dark">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
            </div>
            <br>

              <div class="footer-links">
                <a href="#"><i class="fab fa-github"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin"></i></a>
              </div>
              <div class="text-center">
                MiFleet.fr copyright © 2021 all rights reserved. Made with <i class="fas fa-heart"></i> in France
              </div>
          </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">
      <% if user_signed_in? && (current_user.admin? || current_user.renter?) %>
        <div class="proprio-toggle">
          <button type="button" id="toggleBtn" name="locat_proprio" class="btn btn-lg btn-toggle" data-toggle="button" aria-pressed="false" autocomplete="off">
            <div class="handle"></div>
          </button>
        </div>
      <% end %>
      <!-- Links when logged in -->
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to 'Dashboard', dashboard_index_path , class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      
      <%= link_to "Nos vehicules", cars_path , data: { turbolinks: false }, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Vos locations", rentals_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->

      <% if user_signed_in? %>
      
        <div onClick= "profileFunction()" class="dropbtn dropdown navbar-wagon-item avatar-out">
    
          <a class=""><%= image_tag current_user.avatar_thumbnail, class: "avatar avatar-out" %></a>
          <ul class="dropdown-content dropdown-menu dropdown-menu-right" id="myDropdown">
              <li><%= link_to "Compte", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><%= link_to "Vérifier son profil", license_index_path,  class: "dropdown-item" %></li>
              <li><%= link_to "Manage", "#", class: "dropdown-item" %></li>
              <li class='divider'></li>
              <li><%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>

        </div>
      <% else %>
        <div onClick= "profileFunction()"  class="dropdown dropbtn navbar-wagon-item">     
            <a class=""><%= image_tag "unknown.jpg", class: "avatar avatar-out" %></a>
            <ul class="dropdown-content dropdown-menu dropdown-menu-right" id="myDropdown">
                <li><%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %></li>
                <li><%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %></li>
            </ul>
        </div>
      <% end%>

      
    
      <!-- Login link (when logged out) -->
      <!-- Avatar with dropdown menu -->
      
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <!-- A FAIRE EN JS !! -->
  <div onClick= "profileFunction2()" class="dropdown mobile dropbtn navbar-wagon-item hidden-md hidden-lg hidden-sm">
    
    <% if user_signed_in? %>
      <%= image_tag current_user.avatar_thumbnail, class: "avatar avatar-out avmobile" %>
    <% else %>
      <%= image_tag "unknown.jpg", class: "avatar avatar-out avmobile" %>
    <% end %>
    
    <a  class=""> <i class="mobile fa fa-bars dropdown-toggle"></i></a>
    <div class="dropdown-content dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu", id ="myDropdown2">

      <% if user_signed_in? && (current_user.admin? || current_user.renter?) %>
        <div class="proprio-toggle">
          <button type="button" id="toggleBtnMobile" name="locat_proprio" class="btn btn-lg btn-toggle" data-toggle="button" aria-pressed="false" autocomplete="off">
            <div class="handle"></div>
          </button>
        </div>
      <% end %>

      <% if user_signed_in? && current_user.admin? %>
        <li><%= link_to 'Dashboard', dashboard_index_path  , class: "dropdown-item" %> </li>
        <li class='divider'></li>
      <% end %>

      <li><%= link_to "Nos vehicules", cars_path, data: { turbolinks: false }, class: "dropdown-item" %> </li>
      <li><%= link_to "Vos locations", rentals_path, class: "dropdown-item" %></li> 
      <li><%= link_to "Messages", "#", class: "dropdown-item" %></li>
      <li class='divider'></li>

      <% if user_signed_in? %>
        <li><%= link_to "Compte", edit_user_registration_path, class: "dropdown-item" %></li>
        <li><%= link_to "Vérifier son profil", "#", class: "dropdown-item" %></li>
        <li><%= link_to "Manage", "#", class: "dropdown-item" %></li>
        <li class='divider'></li>
        <li><%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
      <% else %>
        <li><%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %></li>
        <li><%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %></li>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_navbar_dash.html.erb
<div class="admin-menu hidden-xs">
    <h1>Controle Panel</h1>
    <nav>
        <ul class="nav flex-column flex-md-row">
            <li class="nav-item ">
                <%= link_to "#" , class:"nav-link nav-dash" do %>
                    <i class="fas fa-chart-line fa-lg fa-dash"></i><h5>Tableau de bord</h5>
                <% end %>
            </li>
            <li class="nav-item ">
                <%= link_to customer_path , class:"nav-link nav-dash" do %>
                    <i class="fas fa-users fa-lg fa-dash"></i><h5>Clients</h5>
                <% end %>
            </li>
            <li class="nav-item ">
                <%= link_to verification_index_path , class:"nav-link nav-dash" do %>
                    <i class="fas fa-user-check fa-lg fa-dash"></i><h5>Vérifications</h5>
                <% end %>
            </li>
            <li class="nav-item ">
                <%= link_to vehicle_path , class:"nav-link nav-dash" do %>
                    <i class="fas fa-car fa-lg fa-dash"></i><h5>Voitures</h5>
                <% end %>
            </li>
            <li class="nav-item"><%= link_to "Voitures MiFleet", '#', class:"nav-link"%></li>
            <li class="nav-item ">
                <%= link_to traccar_index_path , class:"nav-link nav-dash" do %>
                    <i class="fas fa-wifi fa-lg fa-dash"></i></i><h5>Connect traccar</h5>
                <% end %>
            </li>
            <li class="nav-item ">
                <%= link_to '#' , class:"nav-link nav-dash" do %>
                    <i class="fas fa-unlock-alt fa-lg fa-dash"></i></i><h5>Traccar lock</h5>
                <% end %>
            </li>
            <li class="nav-item"><%= link_to "Commandes", orders_path, class:"nav-link"%></li>
            <li class="nav-item"><%= link_to "Transactions", '#', class:"nav-link"%></li>
            <li class="nav-item"><%= link_to "Promotions", '#', class:"nav-link"%></li>
            <li class="nav-item ">
                <%= link_to statistics_path , class:"nav-link nav-dash" do %>
                    <i class="fas fa-chart-area fa-lg fa-dash"></i><h5>Statistiques</h5>
                <% end %>
            </li>
            <li class="nav-item"><%= link_to "Paiement", '#', class:"nav-link"%></li>
            <li class="nav-item ">
                <%= link_to '#' , class:"nav-link nav-dash" do %>
                    <i class="fas fa-user-shield fa-lg fa-dash"></i><h5>Administration</h5>
                <% end %>
            </li>
            <li class="nav-item"><%= link_to "Paramètres", '#', class:"nav-link"%></li>
        </ul>
    </nav>
</div>




<div class="admin-menu-mobile hidden-sm hidden-lg hidden-md">
    <h4>Controle Panel</h4>
    <a  class="menu-dashboard"> <i onClick= "profileFunctionMob()" class="mobile-fa fa fa-bars dropdown-toggle-mob"></i></a>
    <div class="dropdown-content-mobile dropdown-menu-mobile", id ="myDropdown-mob">
        <li class="dropdown-item"><%= link_to "Tableau de bord", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Clients", customer_path, class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Vérifications", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Voitures", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Voitures MiFleet", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Connect traccar", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Traccar lock", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Commandes", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Transactions", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Promotions", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Statistiques", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Paiement", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Administration", '#', class:"nav-link"%></li>
        <li class="dropdown-item"><%= link_to "Paramètres", '#', class:"nav-link"%></li>
    </div>

</div>

app/views/shared/_searchbar.html.erb
<div class="background-searchbar">
  <div class="form-row align-items-center" >
  <%= form_tag "/search", :method => "get" do %>
    <div class="form-group mx-sm-3 mb-3 search_address" >
      <input id= "car_address", name="search_address", placeholder ="  Adresse de départ", value = "<%= @address %>" >
    </div>
    <div class="mobile-date-form">
        <div class="form-group mx-sm-3 mb-3 col-sm search_date">
          <input  id= "date-starting", readonly='true' , name="search_start_date", placeholder="Début", value = "<%=@start_date %>" >
        </div>
        <div class="form-group mx-sm-3 mb-3 col-sm search_time">
          <input  id= "timepicker", readonly='true' , name="search_start_time", placeholder="Début Heure", value = "<%=@search_start_time %>" >
        </div>
    </div>
    <div class="mobile-date-form">
        <div class="form-group mx-sm-3 mb-3 search_date" >
          <input id= "date-ending", readonly='true' , name="search_end_date", placeholder="Fin", value = "<%= @end_date %>" >
        </div>
       <div class="form-group mx-sm-3 mb-3 col-sm search_time">
          <input  id= "timepicker2", readonly='true' , name="search_start_time", placeholder="Début Heure", value = "<%=@search_start_time %>" >
        </div>
    </div>
        <div class="form-group mx-sm-3 mb-3 search_distance" >
          <%= select_tag :search_distance ,options_for_select([['Distance', 'inconnu'], ['25 km', 25], ['50 km', 50], ['100 km', 100], ['200 km', 200], ['300 km', 300], ['400 km', 400],['500 km', 500], ['600 km', 700], ['300 km', 800], ['400 km', 900],['1000 km', 1000], ['1100 km', 1100], ['1200 km', 1200], ['1300 km', 1300],['1400 km', 1400], ['1500 km', 1500], ['2000 km', 2000], ['3000 km', 3000]], disabled: 'inconnu', selected: 'inconnu', :prompt => 'Distance'),class:'form-control' %>
        </div>
        <div class="form-group mx-sm-3 mb-3" style="margin-top: 0.8%;">
          <%= button_tag(type: "submit", class: "search_submit") do %><i class="fas fa-search"></i><% end %>
        </div>
        <% end %>
      </div>
    </div>

app/views/shared/test_admin.html.erb
<nav class="navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="#">Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                    <% if (action_name == "index") %>
                        <li class="nav-item active">
                    <% else %>
                        <li class="nav-item">
                    <% end %>
                        <a class="nav-link" href="<%= dashboard_index_path %>"><i class="fas fa-tachometer-alt"></i>Accueil</a>
                    </li>
                    <% if (action_name == "page1") %>
                        <li class="nav-item active">
                    <% else %>
                        <li class="nav-item">
                    <% end %>
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-address-book"></i>Page 1</a>
                    </li>
                    <% if (action_name == "mifleetcars") %>
                        <li class="nav-item active">
                    <% else %>
                        <li class="nav-item">
                    <% end %>
                        <a class="nav-link" href="<%= mifleetcars_path %>"><i class="far fa-clone"></i>Véhicules connectés</a>
                    </li>
                    <% if (action_name == "page 3") %>
                        <li class="nav-item active">
                    <% else %>
                        <li class="nav-item">
                    <% end %>
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Page 3</a>
                    </li>
                    <% if (action_name == "page 4") %>
                        <li class="nav-item active">
                    <% else %>
                        <li class="nav-item">
                    <% end %>
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>Page 4</a>
                    </li>
                    <% if (action_name == "page 5") %>
                        <li class="nav-item active">
                    <% else %>
                        <li class="nav-item">
                    <% end %>
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-copy"></i>Page 5</a>
                </li>
            </ul>
        </div>
    </nav>