config/routes.rb
Rails.application.routes.draw do

  resources :room_messages
  devise_for :users , :controllers => { registrations: 'edit_customs' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'edit_customs#edit'
  end

  # Devise (login/logout) for HTML requests
  # devise_for :users, defaults: { format: :html },
  #                        path: '',
  #                  path_names: { sign_up: 'register' },
  #                 controllers: {
  #                   sessions: 'sessions',
  #                   registrations: 'edit_customs',
  #                   confirmations: 'confirmations'
  #                 }
  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'register', to: 'devise/registrations#new'
  #   post 'register', to: 'devise/registrations#create'
  #   delete 'sign_out', to: 'devise/sessions#destroy'
  #   get 'confirmation/sent', to: 'confirmations#sent'
  #   get 'confirmation/:confirmation_token', to: 'confirmations#show'
  #   patch 'confirmation', to: 'confirmations#create'
  # end

  # API namespace, for JSON requests at /api/sign_[in|out]
  namespace :api do
    devise_for :users, defaults: { format: :json },
                     class_name: 'ApiUser',
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: '',
                     path_names: { sign_in: 'login',
                                  sign_out: 'logout' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      delete 'logout', to: 'devise/sessions#destroy'
    end
  end

  root 'pages#home'

  resources :cars
  resources :rentals
  get '/search' => 'pages#search', :as => 'search_page'
  get :search_json, controller: :main

  get '/myrentals/:id', to: 'rentals#show_as_renter', as: "show_as_renter"

  resources :cars_app
  resources :rentals_app

  get '/myrentals_app/:id', to: 'rentals_app#show_as_renter', as: "show_as_renter_from_app"

  resources :charges
  #post '/authentication_tokens', to: "authentication_tokens#create"

  resources :room_messages


  resources :rentals_step
  
  get '/stepA/:id' => 'rentals_step#stepA', as: "stepA"
  get '/stepB/:id' => 'rentals_step#stepB', as: "stepB"
  get '/stepC/:id' => 'rentals_step#stepC', as: "stepC"
  get '/stepD/:id' => 'rentals_step#stepD', as: "stepD"
  get '/stepE/:id' => 'rentals_step#stepE', as: "stepE"
  post '/create_open_traccar' => 'rentals_step#create_open_traccar'


  resources :dashboard
  get '/gettoken' => 'dashboard#create_auth_code', :as => 'gettoken' #A transformer en post pour stocker token n°2 dans database
  get '/login_token' => 'dashboard#create_token', :as => 'login_token' #A transformer en post pour stocker token n°2 dans database
  get '/mifleetcars' => 'dashboard#mifleetcars', :as => 'mifleetcars'
  put '/update_car_device' => 'dashboard#update_car_device'

  get :customer, controller: :dashboard
  get '/customer/:id' => 'dashboard#show_customer', :as => 'getcustomer'
  get :vehicle, controller: :dashboard
  get :orders, controller: :dashboard
  get '/statistics'  => 'dashboard#statistics'

  get 'search_customer', to: 'dashboard#search_customer', defaults: { format: 'js' }
  get 'search_vehicle', to: 'dashboard#search_vehicle', defaults: { format: 'js' }
  get 'search_orders', to: 'dashboard#search_orders', defaults: { format: 'js' }
  get 'search_traccar', to: 'traccar#search_traccar', defaults: { format: 'js' }
  get 'search_traccar_connected', to: 'traccar#search_traccar_connected', defaults: { format: 'js' }


  resources :license
  resources :traccar
  get '/traccar_edit/:id' => 'traccar#traccar_edit', as: "traccar_edit"
  post '/traccar_command' => 'traccar#traccar_command'
  post '/add_traccar_device' => 'traccar#add_traccar_device'
  put '/add_device_id' => 'traccar#add_device_id'
  get '/traccar_api' => 'traccar#traccar_api'

  resources :verification
  #get :submit_verification, controller: :verification


end

app/controllers/cars_app_controller.rb
class CarsAppController < ApplicationController

    before_action :set_car, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, :except => [:show, :index]
  
   
    def index
      @cars = Car.all.order :name

      @result = []
      @result_image = []
      @most_rent = []

      @cars.each do |car|
        @result << car
        @result_image << url_for(car.cars_thumbnail.first)
        @most_rent << Rental.where(car_id: car.id).count

      end

    
      



      #@result = @result.sort_by(&:distance)

      # ------------------------ REACT JS ---------------------------------


      gon.results_all_cars = @result
      gon.results_image_all_cars = @result_image
      gon.most_rent = @most_rent

      if user_signed_in?
        gon.current_user_id = current_user.id
      else  
        gon.current_user_id = nil
      end

      # if user_signed_in?
      #   @ip_address= request.location
      #   user_location = Geocoder.search(@ip_address.ip).first.coordinates
      #   gon.cars_around = Car.all.near(user_location,20, units: :km)
      # end
      
      
      

    end
  
    def show
 
  
      @users = User.all
 
      @hash = Gmaps4rails.build_markers(@car) do |car, marker|
        marker.lat car.latitude
        marker.lng car.longitude
      end

      @rental = Rental.new

  
      @invalidDates = Rental.all.where(car_id: @car.id)
      gon.invalidDates=@invalidDates
      session[:from]=params[:from]

      gon.date_start = Date.today
      gon.date_end = Date.today + 1
      @time_start = ['7:30', '7:30:00']
      @time_end = ['10:00', '10:00:00']
      @distance_rental = ['Distance',0]

      

    end
  
    def new
        @car = Car.new
        
    end
  
    def edit

    end
  
    def create   
        @car = current_user.cars.new(car_params)
        authorize @car
        if @car.save
            #redirect_to new_car_rental_path(@car)
            flash[:notice] = "Le vehicule #{@car.name} a été créé avec succès!"
            redirect_to cars_app_index_path
        else
            render :new
        end
    end
  
    def update
        
        authorize @car
        if @car.update(car_params)
            flash[:notice] = "Le vehicule #{@car.name} a été modifié avec succès!"
            puts "hello2"
            redirect_to cars_app_index_path
        else
            puts "hello3"
            render :edit
        end
    end
  
     def destroy
        @car.user_id = current_user.id
        authorize @car
        if Rental.where(:car_id => @car.id).present?
          flash[:alert]="La voiture est en cours de location!"
          redirect_to cars_app_index_path
        else
          @car.destroy
          respond_to do |format|
              format.html { redirect_to cars_app_index_path, notice: 'Le vehicule a été supprimé avec succès.' }
              format.json { head :no_content }
          end
        end
    end
  
   private
  
      def set_car
        @car = Car.find(params[:id])
      end
  
      def car_params
        params.require(:car).permit(:name,:city , :description, :address, :plaque, :price_cents, :gearbox, :consommation, :engine, :nb_door, :places, :type_car, :price_by_km, :year,:statut, car_images: [])
      end
  end
  

app/views/cars_app/_form.html.erb
<div class="container-new-car">
  <div class="wrap-new-car">
    <div class="form-new-car">
      <span class="title-new-car">Ajouter une voiture</span>
      </div>
      <%= form_for ([@car]), :url => cars_app_index_path do |f| %>
        <h4 class="title-input-car">Informations du vehicule</h4>
        <div class="car-input width-395">
          <span class="label-new-car">Nom du véhicule *</span>
          <div class="input-arrow">
            <%= f.text_field :name, :placeholder => "Renault Kangoo 1.5dci 4m3", :type => "text", :maxlength => "26", :class => "input-new-car", :id => "name_car" %>
            <div onClick="clear_form_elements('#name_car')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-395">
          <span class="label-new-car">Plaque *</span>
          <div class="input-arrow">
            <%= f.text_field :plaque, :placeholder => "AA-123-ZZ", :type => "text", :class => "input-new-car" , :id => "plaque" %>
            <div onClick="clear_form_elements('#plaque')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-130">
          <span class="label-new-car">Année</span>
          <%= f.text_field :year, :placeholder => "année", :type => "text", :class => "input-new-car"  %>
        </div>
        <div class="car-input width-245">
          <span class="label-new-car">Type *</span>
          <div class="input-arrow">
            <%= f.select(:type_car, options_for_select([ "Utilitaire", "Compacte", "Citadine", "Minibus" ]), {},  {:class => "input-new-car" ,:id => "type_car" })%>
            <div onClick="clear_form_elements('#type_car')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-187">
          <span class="label-new-car">Prix *</span>
          <%= f.text_field :price_cents, :placeholder => "Prix par jour", :type => "text", :class => "input-new-car"  %>
        </div>
        <div class="car-input width-187">
          <span class="label-new-car">Prix au km *</span>
          <%= f.text_field :price_by_km, :placeholder => "Prix au km", :type => "text", :class => "input-new-car"  %>
        </div>
        <h4 class="title-input-car">Caracteristique du vehicule</h4>
        <div class="car-input width-157">
          <span class="label-new-car">Moteur *</span>
          <div class="input-arrow">
            <%= f.text_field :engine, :placeholder => "Moteur", :type => "text", :class => "input-new-car" , :id => "engine" %>
            <div onClick="clear_form_elements('#engine')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-127">
          <span class="label-new-car">Portes</span>
          <div class="input-arrow">
            <%= f.text_field :nb_door, :placeholder => "4", :type => "text", :class => "input-new-car" , :id => "nb_door" %>
            <div onClick="clear_form_elements('#nb_door')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-197">
          <span class="label-new-car">Boite de vitesse *</span>
          <div class="input-arrow">
            <%= f.text_field :gearbox, :placeholder => "Manuelle", :type => "text", :class => "input-new-car" , :id => "gearbox" %>
            <div onClick="clear_form_elements('#gearbox')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-267">
          <span class="label-new-car">Consommation *</span>
          <div class="input-arrow">
            <%= f.text_field :consommation, :placeholder => "Consommation L/100 km", :type => "text", :class => "input-new-car", :id => "consommation"  %>
            <div onClick="clear_form_elements('#consommation')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input", style="width: 100%;">
          <span class="label-new-car">Adresse de stationnement *</span>
          <div class="input-arrow">
            <%= f.text_field :address, :placeholder => "Adresse de stationnement", :type => "text", :class => "input-new-car", :id => "car_address"  %>
            <div onClick="clear_form_elements('#car_address')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input", style="width: 100%;">
          <span class="label-new-car">Description</span>
          <div class="input-arrow">
            <%= f.text_area :description, :placeholder => "Ajouter une description", :type => "text", :class => "input-new-car", :id => "description"  %>
          </div>
        </div>
        <div class="car-input", style="width: 100%;">
          <span class="label-new-car">Importer des images du véhicule * </span>
          <div class="input-arrow">
            <label class="file"><%= f.file_field :car_images, multiple: true %></label>
          </div>
        </div>
        <div class="div-btn-new-car">
          <%= button_tag type: 'submit', class: "btn-new-car" do %>
            <span style="display:flex;">Envoyer <i class="fas fa-long-arrow-alt-right" aria-hidden="true"></i></span>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  function clear_form_elements(ele) {
    $(ele).val('');
}
</script>

app/views/cars_app/_form_edit.html.erb
<div class="container-new-car">
  <div class="wrap-new-car">
    <div class="form-new-car">
      <span class="title-new-car">Modifier votre voiture</span>
      </div>
        <%= form_for ([@car]), :url => cars_app_path(@car), :method => "patch" do |f| %>
        <h4 class="title-input-car">Informations du vehicule</h4>
        <div class="car-input width-395">
          <span class="label-new-car">Nom du véhicule *</span>
          <div class="input-arrow">
            <%= f.text_field :name, :placeholder => "Renault Kangoo 1.5dci 4m3", :type => "text", :maxlength => "26", :class => "input-new-car", :id => "name_car" %>
            <div onClick="clear_form_elements('#name_car')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-395">
          <span class="label-new-car">Plaque *</span>
          <div class="input-arrow">
            <%= f.text_field :plaque, :placeholder => "AA-123-ZZ", :type => "text", :class => "input-new-car" , :id => "plaque" %>
            <div onClick="clear_form_elements('#plaque')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-130">
          <span class="label-new-car">Année</span>
          <%= f.text_field :year, :placeholder => "année", :type => "text", :class => "input-new-car"  %>
        </div>
        <div class="car-input width-245">
          <span class="label-new-car">Type *</span>
          <div class="input-arrow">
            <%= f.select(:type_car, options_for_select([ "Utilitaire", "Compacte", "Citadine", "Minibus" ]), {},  {:class => "input-new-car" ,:id => "type_car" })%>
            <div onClick="clear_form_elements('#type_car')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-187">
          <span class="label-new-car">Prix *</span>
          <%= f.text_field :price_cents, :placeholder => "Prix par jour", :type => "text", :class => "input-new-car"  %>
        </div>
        <div class="car-input width-187">
          <span class="label-new-car">Prix au km *</span>
          <%= f.text_field :price_by_km, :placeholder => "Prix au km", :type => "text", :class => "input-new-car"  %>
        </div>
        <h4 class="title-input-car">Caracteristique du vehicule</h4>
        <div class="car-input width-157">
          <span class="label-new-car">Moteur *</span>
          <div class="input-arrow">
            <%= f.text_field :engine, :placeholder => "Moteur", :type => "text", :class => "input-new-car" , :id => "engine" %>
            <div onClick="clear_form_elements('#engine')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-127">
          <span class="label-new-car">Portes</span>
          <div class="input-arrow">
            <%= f.text_field :nb_door, :placeholder => "4", :type => "text", :class => "input-new-car" , :id => "nb_door" %>
            <div onClick="clear_form_elements('#nb_door')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-197">
          <span class="label-new-car">Boite de vitesse *</span>
          <div class="input-arrow">
            <%= f.text_field :gearbox, :placeholder => "Manuelle", :type => "text", :class => "input-new-car" , :id => "gearbox" %>
            <div onClick="clear_form_elements('#gearbox')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input width-267">
          <span class="label-new-car">Consommation *</span>
          <div class="input-arrow">
            <%= f.text_field :consommation, :placeholder => "Consommation L/100 km", :type => "text", :class => "input-new-car", :id => "consommation"  %>
            <div onClick="clear_form_elements('#consommation')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input", style="width: 100%;">
          <span class="label-new-car">Adresse de stationnement *</span>
          <div class="input-arrow">
            <%= f.text_field :address, :placeholder => "Adresse de stationnement", :type => "text", :class => "input-new-car", :id => "car_address"  %>
            <div onClick="clear_form_elements('#car_address')" value="clear" class="clear_input"></div>
          </div>
        </div>
        <div class="car-input", style="width: 100%;">
          <span class="label-new-car">Description</span>
          <div class="input-arrow">
            <%= f.text_area :description, :placeholder => "Ajouter une description", :type => "text", :class => "input-new-car", :id => "description"  %>
          </div>
        </div>
        <div class="car-input", style="width: 100%;">
          <span class="label-new-car">Importer des images du véhicule * </span>
          <div class="input-arrow">
            <label class="file"><%= f.file_field :car_images, multiple: true %></label>
          </div>
        </div>
        <div class="div-btn-new-car">
          <%= button_tag type: 'submit', class: "btn-new-car" do %>
            <span style="display:flex;">Mettre à jour <i class="fas fa-long-arrow-alt-right" aria-hidden="true"></i></span>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  function clear_form_elements(ele) {
    $(ele).val('');
}
</script>

app/views/cars_app/_form_new_rental.html.erb
<div class=" hidden-xs">
     <%= form_for([@rental]) do |f| %>
          <%= f.label "Selectionner une date" %>
          <div class="invalid-date-message">
               <p>Votre date est invalide</p>
          </div>
          <!-- ordi date -->
          <div class="rent_date">
               <input id= "rent-date-starting", name="rent_start_date", placeholder="Début" >
               <%= select_tag :rent_start_time ,options_for_select([['7:30', '7:30:00'], ['8:00', '8:00:00'], ['8:30', '8:30:00'], ['9:00', '9:00:00'], ['9:30', '9:30:00'], ['10:00', '10:00:00']],  selected: @time_start[1], :prompt =>  @time_start[0]) ,class:'form-control' %>                 
               <div class="spacing-div"></div>
               <input id= "rent-date-ending", name="rent_end_date", placeholder="Fin" > 
               <%= select_tag :rent_end_time ,options_for_select([['7:30', '7:30:00'], ['8:00', '8:00:00'], ['8:30', '8:30:00'], ['9:00', '9:00:00'], ['9:30', '9:30:00'], ['10:00', '10:00:00']],  selected: @time_end[1], :prompt => @time_end[0]) ,class:'form-control' %>  
          </div>
          <!-- fin ordi date -->
          <%= f.label "Selectionner une distance" %>
          <%= f.select :distance ,options_for_select([['Distance', 0], ['25 km', 25], ['50 km', 50], ['100 km', 100], ['200 km', 200], ['300 km', 300], ['400 km', 400],['500 km', 500], ['600 km', 600], ['800 km', 800], ['900 km', 900],['1000 km', 1000], ['1100 km', 1100], ['1200 km', 1200], ['1300 km', 1300],['1400 km', 1400], ['1500 km', 1500], ['2000 km', 2000], ['3000 km', 3000]],  selected: @distance_rental[1], :prompt => @distance_rental[0]),class:'form-control rent_distance' %>
          <%= hidden_field_tag 'car_attributes', @car.id %>
           <%= f.submit "Réserver",class: "button-rent-mobile", disabled:false %>
     <% end %>
</div>


<div class=" hidden-md hidden-lg hidden-sm">
     <%= form_for([@rental]) do |f| %>
          <%= f.label "Selectionner une date" %>
          <div class="invalid-date-message-mobile">
               <p>Votre date est invalide</p>
          </div>
         
          <!-- mobile date -->
          <div class="rent_date">
               <input id= "rent-date-starting-mobile", name="rent_start_date", placeholder="Début" >
               <%= select_tag :rent_start_time ,options_for_select([['7:30', '7:30:00'], ['8:00', '8:00:00'], ['8:30', '8:30:00'], ['9:00', '9:00:00'], ['9:30', '9:30:00'], ['10:00', '10:00:00']],  selected: @time_start[1], :prompt =>  @time_start[0]) ,class:'form-control' %>                 
               <div class="spacing-div"></div>
               <input id= "rent-date-ending-mobile", name="rent_end_date", placeholder="Fin" > 
               <%= select_tag :rent_end_time ,options_for_select([['7:30', '7:30:00'], ['8:00', '8:00:00'], ['8:30', '8:30:00'], ['9:00', '9:00:00'], ['9:30', '9:30:00'], ['10:00', '10:00:00']],  selected: @time_end[1], :prompt => @time_end[0]) ,class:'form-control' %>  
          </div>
          <!-- fin mobile date -->
          <%= f.label "Selectionner une distance" %>
          <%= f.select :distance ,options_for_select([['Distance', 0], ['25 km', 25], ['50 km', 50], ['100 km', 100], ['200 km', 200], ['300 km', 300], ['400 km', 400],['500 km', 500], ['700 km', 700], ['800 km', 800], ['900 km', 900],['1000 km', 1000], ['1100 km', 1100], ['1200 km', 1200], ['1300 km', 1300],['1400 km', 1400], ['1500 km', 1500], ['2000 km', 2000], ['3000 km', 3000]],  selected: @distance_rental[1], :prompt => @distance_rental[0]),class:'form-control rent_distance' %>
          <%= hidden_field_tag 'car_attributes', @car.id %>
           <%= f.submit "Réserver",class: "button-rent-mobile", disabled:false %>
          
     <% end %>
</div>

app/views/cars_app/edit.html.erb
  <% if @car.errors.any? %>
    <%= flash.discard(flash[:alert] = "Il manque #{@car.errors.count} #{("champ").pluralize(@car.errors.count)}!") %>
  <% end %>

    <%= render 'form_edit' %>



<% content_for :javascript_includes do %>
    <%= javascript_pack_tag "appMobile/cars_app/cars_app_edit_view.js" %>
<% end %>

app/views/cars_app/index.html.erb
<!-- METTRE TOGLLE LOCATAIRE PROPRIO BUTTON TOGGLE -->

<% content_for :head do %>
  <meta name="turbolinks-visit-control" content="reload">
<% end %>

<% if user_signed_in? && (current_user.admin? || current_user.renter?) %>
     <%= link_to 'Ajouter une voiture', new_car_path, class: 'btn btn-primary btn-lg btn-block' %>
     
<% end %>

<% unless user_signed_in? %>
    <div id="cars_results_sign_out"></div>
<% end %>

<% if user_signed_in? && current_user.client? %>
    <div id="cars_results_sign_out"></div>
<% end %>

<% if user_signed_in? && (current_user.renter? || current_user.admin?) %>
    <div id="my_cars_results" style="display : block;"></div>
<% end %>

<% content_for :javascript_includes do %>
    <%= javascript_pack_tag "appMobile/cars_app/cars_app_index_view.js" %>
<% end %>

<script src="//maps.google.com/maps/api/js?key=AIzaSyDEHC931ZRGi3Ihtl8rrA-WV3HM5jL8HQc&callback=initMap"></script>  

app/views/cars_app/new.html.erb
<% if @car.errors.any? %>
    <%= flash.discard(flash[:alert] ="Il manque #{@car.errors.count} #{("champ").pluralize(@car.errors.count)}!") %>
  <% end %>


  <%= render "form" %>


<% content_for :javascript_includes do %>
  <%= javascript_pack_tag "appMobile/cars_app/cars_app_new_view.js" %>
<% end %>

app/views/cars_app/show.html.erb
<% if user_signed_in? && (current_user.admin? || (current_user.renter? && current_user.id == @car.user_id)) %>
     <%= link_to 'Editer la voiture', edit_cars_app_path, class: 'btn btn-primary btn-lg btn-block' %>
     <%= button_to 'Supprimer la voiture', cars_app_path(@car), method: :delete, class: 'button-delete-car btn-lg',:onclick => "return confirm('Etes vous sur?')", :remote => true %>
<% end %>
<div class="header">
    <div class="scroller">
        <!-- mettre image -->
        <div class="carousel_car box-show">
            <%= carousel_for(@car.cars_thumbnail_show) %>
            <h2><%= @car.name %></h2>
            <h3><%= @car.year %>, Moteur <%= @car.engine %>, <%= @car.places %> Places, <%= @car.gearbox %></h3>
            <br>
        </div>
    </div>
    <div class="car_description">
        <div class="box-show">
            <p>adresse : <%= @car.address %><p>
            <div id="map" class="map-style">
            </div>
 
            
        </div>
        
        <% if user_signed_in? && current_user.admin? %> 
            <div class="box-show">     
                <p><%= @car.odometer %> km<p>
                <p><%= @car.fueltank %> L car Tank<p>
                <p><%= @car.computerfueltank %> L car_computer Tank<p>
            </div>
        <% end %>

        <div class="box-show"> 
            <p><%= @car.city %><p>
            <h4>Caractéristiques techniques</h4>
            <p>Moteur <%= @car.engine %><p>
            <p>Porte <%= @car.nb_door %><p>
            <p><%= @car.places %> Places<p>
            <p>Boite de Vitesse <%= @car.gearbox %><p>
            <p>Consommation <%= @car.consommation %><p>
            
        </div>
        <div class="box-show"> 
            <h4>Description</h4>
            <p><%= @car.description %><p>
            <div id="calendar"></div>
        </div>

    </div>
    
     <% if (@car.statut == "available" && !user_signed_in?) || (@car.statut == "available" && user_signed_in? && current_user.id != @car.user_id) %>
        <!--<div class="d-flex text-center space-btn">
            <%= link_to 'Louer ce vehicule', new_rental_path(car: @car, from: "show_car"), class: 'btn btn-success' %>
        </div>-->

        <% if @rental.errors.any? %>
            <%= flash.discard(flash[:alert] = "Il manque #{@rental.errors.count} #{("champ").pluralize(@rental.errors.count)}!") %>
        <% end %>
        <div style="padding-top:30px;">
            <div class="form-rental-div">
                <h3>Nouvelle location : <%= @car.name %></h3>
                <%= render 'form_new_rental' %>
            </div>
        </div>
    <% end %>
        
</div>

<script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script> 
<script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>
<script src="//maps.google.com/maps/api/js?key=AIzaSyDEHC931ZRGi3Ihtl8rrA-WV3HM5jL8HQc&callback=initMap"></script>  

<script type="text/javascript">  
function initMap() {
handler = Gmaps.build('Google');  
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);  
        // to center on a marker
        handler.map.centerOn(markers[0]); 
        // to set the map zoom
        handler.getMap().setZoom(16);

    }); 
} 

google.maps.event.addDomListener(window, 'load', function() {
  initMap();
});

$(document).bind("projectLoadComplete", initMap());
</script>


<% content_for :javascript_includes do %>
    <%= javascript_pack_tag "appMobile/cars_app/cars_app_show_view.js" %>
<% end %>