config/routes.rb
Rails.application.routes.draw do

  resources :room_messages
  devise_for :users , :controllers => { registrations: 'edit_customs' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'edit_customs#edit'
  end

  # Devise (login/logout) for HTML requests
  # devise_for :users, defaults: { format: :html },
  #                        path: '',
  #                  path_names: { sign_up: 'register' },
  #                 controllers: {
  #                   sessions: 'sessions',
  #                   registrations: 'edit_customs',
  #                   confirmations: 'confirmations'
  #                 }
  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'register', to: 'devise/registrations#new'
  #   post 'register', to: 'devise/registrations#create'
  #   delete 'sign_out', to: 'devise/sessions#destroy'
  #   get 'confirmation/sent', to: 'confirmations#sent'
  #   get 'confirmation/:confirmation_token', to: 'confirmations#show'
  #   patch 'confirmation', to: 'confirmations#create'
  # end

  # API namespace, for JSON requests at /api/sign_[in|out]
  namespace :api do
    devise_for :users, defaults: { format: :json },
                     class_name: 'ApiUser',
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: '',
                     path_names: { sign_in: 'login',
                                  sign_out: 'logout' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      delete 'logout', to: 'devise/sessions#destroy'
    end
  end

  root 'pages#home'

  resources :cars
  resources :rentals
  get '/search' => 'pages#search', :as => 'search_page'
  get :search_json, controller: :main

  get '/myrentals/:id', to: 'rentals#show_as_renter', as: "show_as_renter"

  resources :cars_app
  resources :rentals_app

  get '/myrentals_app/:id', to: 'rentals_app#show_as_renter', as: "show_as_renter_from_app"

  resources :charges
  #post '/authentication_tokens', to: "authentication_tokens#create"

  resources :room_messages


  resources :rentals_step
  
  get '/stepA/:id' => 'rentals_step#stepA', as: "stepA"
  get '/stepB/:id' => 'rentals_step#stepB', as: "stepB"
  get '/stepC/:id' => 'rentals_step#stepC', as: "stepC"
  get '/stepD/:id' => 'rentals_step#stepD', as: "stepD"
  get '/stepE/:id' => 'rentals_step#stepE', as: "stepE"
  post '/create_open_traccar' => 'rentals_step#create_open_traccar'


  resources :dashboard
  get '/gettoken' => 'dashboard#create_auth_code', :as => 'gettoken' #A transformer en post pour stocker token n°2 dans database
  get '/login_token' => 'dashboard#create_token', :as => 'login_token' #A transformer en post pour stocker token n°2 dans database
  get '/mifleetcars' => 'dashboard#mifleetcars', :as => 'mifleetcars'
  put '/update_car_device' => 'dashboard#update_car_device'

  get :customer, controller: :dashboard
  get '/customer/:id' => 'dashboard#show_customer', :as => 'getcustomer'
  get :vehicle, controller: :dashboard
  get :orders, controller: :dashboard
  get '/statistics'  => 'dashboard#statistics'

  get 'search_customer', to: 'dashboard#search_customer', defaults: { format: 'js' }
  get 'search_vehicle', to: 'dashboard#search_vehicle', defaults: { format: 'js' }
  get 'search_orders', to: 'dashboard#search_orders', defaults: { format: 'js' }
  get 'search_traccar', to: 'traccar#search_traccar', defaults: { format: 'js' }
  get 'search_traccar_connected', to: 'traccar#search_traccar_connected', defaults: { format: 'js' }


  resources :license
  resources :traccar
  get '/traccar_edit/:id' => 'traccar#traccar_edit', as: "traccar_edit"
  post '/traccar_command' => 'traccar#traccar_command'
  post '/add_traccar_device' => 'traccar#add_traccar_device'
  put '/add_device_id' => 'traccar#add_device_id'
  get '/traccar_api' => 'traccar#traccar_api'

  resources :verification
  #get :submit_verification, controller: :verification


end

app/controllers/traccar_controller.rb
require 'oauth2'
require 'base64'
require 'uri'
require 'net/http'
require 'openssl'
require 'rest-client'


class TraccarController < ApplicationController
    rescue_from ActiveRecord::RecordNotUnique, with: :invalid_foreign_key
    before_action :authenticate_user!
    before_action :set_car, only: [:edit]
    before_action :set_traccar_car, only: [:traccar_edit, :search_traccar_connected]
    before_action :traccar_commands, only: [:traccar_edit, :traccar_command]


    def index
        @cars = Car.order(created_at: :asc).page(params[:page])

        $url_device = "86.247.136.45:8082/api/devices"
        response = RestClient::Request.execute(url: $url_device, method: :get, headers:{Authorization: "Basic #{Base64.encode64('huangdey973@gmail.com:Parisevan1995')}"})
        
        @data = JSON.parse(response)

        @uniqueId = []

        @data.each do |device|
            @uniqueId << device["uniqueId"]
    
        end

  

        render layout: "dashboard"
    end

    def search_traccar
        query = params[:search_traccar]
        @cars = Car.where('name LIKE ?', "%#{query}%")
        #render layout: false
    end

    def search_traccar_connected
        query = params[:search_traccar_connedted]
        @data = @data.where('name LIKE ?', "%#{query}%")
        #render layout: false
    end

    def edit
        render layout: "dashboard"
    end

    def add_device_id
        authorize User
        @car = Car.find(params[:car_id])
        if @car.update_attribute(:device_id,params[:device_id])
            flash[:notice] = "Le device id du vehicule #{@car.name} a été modifié avec succès!"
            redirect_to traccar_index_path
        else
            flash[:alert] = "Le device id du vehicule #{@car.name} n'a pas été modifé avec succès!"
            redirect_to request.referrer
        end
     
    end

    def traccar_edit

        render layout: "dashboard"
    end

    def traccar_command
   
        response =  RestClient::Request.execute(method: :post, url: '86.247.136.45:8082/api/commands/send', payload: {id: params[:id], deviceId: params[:traccar_id] }.to_json, headers:{Authorization: "Basic #{Base64.encode64('huangdey973@gmail.com:Parisevan1995')}", :accept => "application/json", :content_type => "application/json" })

        @commands.each do |command|  
            if params[:id].to_i == command["id"]
                @command = command
            end
        end
        #render json: response
        flash[:notice] = "La commande < #{@command["description"]} > a été éxécutée avec succès!"
        
        redirect_to request.referrer

        
    end

    def new
        render layout: "dashboard"
    end

    def add_traccar_device

    end

    def traccar_api
    



        $url = "86.247.136.45:8082/api/devices"


        response = RestClient::Request.execute(url: $url, method: :get, headers:{Authorization: "Basic #{Base64.encode64('huangdey973@gmail.com:Parisevan1995')}"})
        #response =  RestClient::Request.execute(method: :post, url: '86.247.136.45:8082/api/commands/send', payload: {id: 2, deviceId: 864180036851835 }.to_json, headers:{Authorization: "Basic #{Base64.encode64('huangdey973@gmail.com:Parisevan1995')}", :accept => "application/json", :content_type => "application/json" })

        puts ("traccar")
        
        @data = JSON.parse(response)

        # @uniqueId = []

        # @data.each do |device|
        #     @uniqueId << device["uniqueId"]
    
        # end


        #render json: nil, status: :ok
        render json: response
        #head :ok


        #----------------------

        # response = RestClient::Request.new({
        #     method: :post,
        #     url:  $url,
        #     user: 'huangdey973@gmail.com',
        #     password: 'Parisevan1995',
        #     payload: { id: 1, deviceId: 864180036851835 , description:"", type:"", attributes: ""},
        #     headers: { :accept => "application/json", :content_type => "application/json" }
        #   }).execute do |response, request, result|
        #     case response.code
        #     when 202
        #       [ :error, parse_json(response.to_str) ]
        #     when 200
        #       [ :success, parse_json(response.to_str) ]
        #     else
        #       fail "Invalid response #{response.to_str} received."
        #     end
        #   end
          
        #   render json: response
      
        
    end

    private
    
    def set_car
        @car = Car.find(params[:id])
    end

    def set_traccar_car 
        $url_device = "86.247.136.45:8082/api/devices"
        response = RestClient::Request.execute(url: $url_device, method: :get, headers:{Authorization: "Basic #{Base64.encode64('huangdey973@gmail.com:Parisevan1995')}"})
        
        @data = JSON.parse(response)

        @data.each do |device|  
            if params[:id].to_i == device["id"]
                @traccar = device
            end
        end

    end

    def car_params
        params.require(:car).permit(:device_id)
    end

    def traccar_commands
        $url = "86.247.136.45:8082/api/commands"

        response = RestClient::Request.execute(url: $url, method: :get, headers:{Authorization: "Basic #{Base64.encode64('huangdey973@gmail.com:Parisevan1995')}"})
    
        
        @commands = JSON.parse(response)

    end

    def invalid_foreign_key
        redirect_to request.referrer, alert: 'Device id déja associé.'
    end
    
end

app/views/traccar/_cars.html.erb
<div class="list-items item-card-pc">
    <table>
        <caption>Liste des véhicules</caption>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col">Nom</th>
            <th scope="col">Plaque</th>
            <th scope="col">Device id</th>
            <th scope="col">Traccar connect</th>
            <th scope="col">Propriétaire</th>
            <th scope="col">Edit device id</th>
        <tr>
        <% @cars.each do |car| %>
            <tr>
                <td class="item-image"><%= image_tag car.cars_thumbnail.first, class: "image-pp" %></td>
                <th scope="row" class="item-name"><%= car.name %></th>
                <td class="item-info"><%= car.plaque %></td>
                <% if car.device_id? %>
                    <td class="item-info"><%= car.device_id %></td>
                <% else %>
                    <td class="item-info">
                        <%= link_to 'Ajouter un device id', edit_traccar_path(car) , class: '' %>
                    </td>
                <% end %>
                <% if @uniqueId.include? car.device_id %>
                    <td class="item-info traccar-connect"><p>connected</p></td>
                <% else %>
                    <td class="item-info">
                        <p>not connected</p>
                    </td>
                <% end %>
                <td class="item-info"><%= car.user.email %></td>
                <td>
                    <%= link_to ('<i class="fas fa-edit fa-2x"></i>').html_safe, edit_traccar_path(car) %>
                </td>

            </tr>

            
        <% end %>
    </table>
</div>

app/views/traccar/_traccar.html.erb
<div class="list-items item-card-pc">
    <table>
        <caption>Liste des véhicules connectés à traccar</caption>
        <tr>
            <th scope="col">Nom</th>
            <th scope="col">Device id</th>
            <th scope="col">Position</th>
            <th scope="col">statut</th>
            <th scope="col">Commandes</th>
        <tr>
        <% @data.each do |traccar| %>
            <tr>
                <th scope="row" class="item-name"><%= traccar['name'] %></th>
                <td class="item-info"><%= traccar['uniqueId'] %></td>
                <td class="item-info"><%= traccar['positionId'] %></td>
                <% if traccar["status"] == "online" %>
                    <td class="item-info traccar-connect"><%= traccar['status'] %></td>
                   
                <% else traccar["status"] == "offline" %>
                    <td class="item-info">
                        <%= traccar['status'] %>
                    </td>
                <% end %>
                 <td>
                    <%= link_to ('<i class="fas fa-edit fa-2x"></i>').html_safe, traccar_edit_path(traccar['id']) %>
                </td>

            </tr>

            
        <% end %>
    </table>
</div>

app/views/traccar/edit.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Traccar</h2>

        <div>
            <%= form_with url: "/add_device_id", method: :put do |f| %>
                <h4 class="title-input-car"><%= @car.name %></h4>
                <div class="car-input width-395">
                    <span class="label-new-car">Rentrez le device id</span>
                <div class="input-arrow">
                    <%= f.text_field :device_id %>                  
                </div>
                <%= f.hidden_field :car_id, :value => @car.id %>
                <div class="div-btn-new-car">
                <%= button_tag type: 'submit', class: "btn-new-car" do %>
                    <span style="display:flex;">Mettre à jour <i class="fas fa-long-arrow-alt-right" aria-hidden="true"></i></span>
                <% end %>
                </div>
            <% end %>
            </div>
        </div>


    </div>


</div>

app/views/traccar/index.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Traccar</h2>
        <%= paginate @cars, theme: 'twitter-bootstrap-4' %>
        <%= form_tag(search_traccar_path, method: "get", remote: true) do %>
            <div class="input-group mb-5">
                <div class="col-8" style="padding:0">
                    <%= text_field_tag :search_traccar, '', class:'form-control', placeholder: 'Recherche de voitures ...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4" style="padding:0">
                    <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit', style:'display:none'%>
                </div>
            </div>
        <% end %>
        
        <div id="menu-traccar-container">
            <%= render 'cars'%>
        </div>


        
        <div id="menu-traccar-connected-container">
            <h4 class="btn-add-device"><%= link_to "Ajouter un device", new_traccar_path %></h4>
            <%= render 'traccar'%>
        </div>

    </div>


</div>

<script>
    function clickSubmit() {
        $("#search_submit").trigger("click");
    }
    function clickSubmitTraccar() {
        $("#search_submit_traccar").trigger("click");
    }
</script>

app/views/traccar/new.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Traccar - Ajouter un device</h2>

        <div>
            <%= form_with url: "/add_traccar_device", method: :post do |f| %>
                <div class="car-input width-395">
                    <span class="label-new-car">Nom</span>
                <div class="input-arrow">
                    <%= f.text_field :name %>                  
                </div>
                <div class="div-btn-new-car">
                <%= button_tag type: 'submit', class: "btn-new-car" do %>
                    <span style="display:flex;">Ajouter device<i class="fas fa-long-arrow-alt-right" aria-hidden="true"></i></span>
                <% end %>
                </div>
            <% end %>
            </div>
        </div>


    </div>


</div>

app/views/traccar/search_traccar.js.erb
$("#menu-traccar-container").html("<%= j render 'cars' %>");

app/views/traccar/traccar_edit.html.erb
<div class="dashboard">   
    <div class="page-menu">
        <h2>Traccar</h2>

        <h4 class="title-input-car"><%= @traccar['name'] %></h4>

        <% if @traccar["status"] == "online" %>
            <% @commands.each do |command| %>
            
                <div class="div-btn-command-traccar">
                    <%= button_to command['description'], {:controller => "traccar", :action => "traccar_command", :id => command["id"], :traccar_id=> @traccar['id']} , :method=>:post, :class => "btn-traccar-command"  %>
                </div>

            <% end %>

        <% else @traccar["status"] == "offline" %>
            <td class="item-info">
                <%= @traccar['status'] %>
            </td>
        <% end %>

    </div>


</div>